---

- name: Prepare
  include_tasks: prepare.yml

- name: Download
  include_tasks: download.yml

- name: Set up flags
  include_tasks: set-up-flags.yml

- name: Wrap and link
  include_tasks: wrap-and-link.yml
