---

- name: Remove old packages
  file:
    name: "{{ chromium_dest }}"
    state: absent
  changed_when: false

- name: Prepare dest
  file:
    name: "{{ chromium_dest }}"
    state: directory
    mode: 0755
  changed_when: false

- name: Ubuntu support
  when: ansible_distribution == 'Ubuntu'
  block:

    - name: Uninstall old packages
      apt:
        name: "{{ chromium_uninstall }}"
        state: absent

    - name: Install dependencies
      apt:
        name:
          - libnss3
          - libatk1.0-0
          - libatk-bridge2.0-0
          - libcups2
          - libdrm2
          - libxcomposite1
          - libxdamage1
          - libxfixes3
          - libxrender1
          - libxrandr2
          - libxkbcommon0
          - libgbm1
          - libgtk-3-0
          - libpci3
          - libasound2
          - libxshmfence1
          - libva2
        state: present

- name: CentOS support
  when: ansible_distribution == 'CentOS'
  block:

    - name: Uninstall old packages
      yum:
        name: "{{ chromium_uninstall }}"
        state: absent

    - name: Install dependencies
      yum:
        name:
          - nss
          - atk
          - at-spi2-atk
          - cups-libs
          - libdrm
          - libXcomposite
          - libXdamage
          - libXrender
          - libXrandr
          - libxkbcommon
          - mesa-libgbm
          - gtk3
          - pciutils-libs
          - alsa-lib
          - libva
        state: present
