---
- name: Allow root
  when: chromium_allow_root
  set_fact:
    chromium_set_flags: "{{ chromium_set_flags + [ 'no-sandbox' ] }}"

- name: Disable GPU
  when: chromium_disable_gpu
  set_fact:
    chromium_set_flags: "{{ chromium_set_flags + [ 'disable-gpu' ] }}"

- name: Disable web security
  when: chromium_disable_web_security
  set_fact:
    chromium_set_flags: "{{ chromium_set_flags + [ 'disable-web-security' ] }}"

- name: Ignore certificate errors
  when: chromium_ignore_certificate_errors
  set_fact:
    chromium_set_flags: "{{ chromium_set_flags + [ 'ignore-certificate-errors' ] }}"

- name: Custom flags
  set_fact:
    chromium_set_flags: "{{ chromium_set_flags + chromium_custom_flags }}"

- name: Create flags string
  set_fact:
    chromium_set_flags_string: "{{ chromium_set_flags_string }} --{{ item }}"
  loop: "{{ chromium_set_flags }}"
